# MySQL 数据源
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # MongoDB 数据源
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test